Update jenkins.yaml

diff --git a/jenkins.yaml b/jenkins.yaml
--- a/jenkins.yaml
+++ b/jenkins.yaml
@@ -1,24 +1,40 @@
+
+on:
+  workflow_dispatch:
+    inputs:
+      Environment:
+        description: "Select Environment"
+        required: true
+        default: "pflqa00"
+        type: choice
+        options:
+          - pflqa00
+          - pflqa12
+          - pflqa22
+          - pflqa36
+          - pflqa42
+
+jobs:
+  deploy:
+    runs-on: test
+    steps:
       - name: Set Environment Variables
         run: |
-          echo 'ORG_PATH="/home/bambscm1/actions-runner-2/_work/bcc-pat/bcc-pat/"' >> $GITHUB_ENV
-          echo "TMP_PATH=/tmp/pat/" >> $GITHUB_ENV
+          if [[ "${{ github.event.inputs.Environment }}" == "pflqa36" ]]; then
+            echo "ADMIN_USR=pfmgr4" >> $GITHUB_ENV
+            echo "PATH_ENV=pflqa36/" >> $GITHUB_ENV
+          elif [[ "${{ github.event.inputs.Environment }}" == "pflqa42" ]]; then
+            echo "ADMIN_USR=pfmgr4" >> $GITHUB_ENV
+            echo "PATH_ENV=pflqa42/" >> $GITHUB_ENV
+          elif [[ "${{ github.event.inputs.Environment }}" == "pflqa00" ]]; then
+            echo "ADMIN_USR=pfmgr" >> $GITHUB_ENV
+            echo "PATH_ENV=pflqa00/" >> $GITHUB_ENV
+          else
+            echo "Invalid environment choice: ${{ github.event.inputs.Environment }}"
+            exit 1
+          fi
 
-      - name: Set Permissions for Temporary Path
+      - name: Print Selected Variables
         run: |
-          mkdir -p $TMP_PATH
-          chmod -R 755 $TMP_PATH
-
-      - name: Set Variables
-        run: |
-          echo "REMOTE_PATH=${ORG_PATH}unix/PFW_UNIX/pjlcheck_pat/opt/pjlcheck_pat" >> $GITHUB_ENV
-          echo "REMOTE_PATH1=${ORG_PATH}unix/PFW_UNIX/plsegfix_pat/opt/plsegfix_pat" >> $GITHUB_ENV
-          echo "REMOTE_PATH2=${ORG_PATH}unix/PFW_UNIX/plsegchk_pat/opt/plsegchk_pat" >> $GITHUB_ENV
-          echo "REMOTE_PATH3=${ORG_PATH}unix/PFW_UNIX/plstatus_pat/opt/plstatus_pat" >> $GITHUB_ENV
-          echo "LOCAL_PATH=/tmp/pat/" >> $GITHUB_ENV
-
-      - name: Copy Binary Files from Remote to Local
-        run: |
-          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/vscode bambdev1@daylnxcpsd002:$REMOTE_PATH $LOCAL_PATH || echo "Skipping $REMOTE_PATH due to permission error"
-          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/vscode bambdev1@daylnxcpsd002:$REMOTE_PATH1 $LOCAL_PATH || echo "Skipping $REMOTE_PATH1 due to permission error"
-          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/vscode bambdev1@daylnxcpsd002:$REMOTE_PATH2 $LOCAL_PATH || echo "Skipping $REMOTE_PATH2 due to permission error"
-          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/vscode bambdev1@daylnxcpsd002:$REMOTE_PATH3 $LOCAL_PATH || echo "Skipping $REMOTE_PATH3 due to permission error"
+          echo "Selected Admin User: $ADMIN_USR"
+          echo "Selected Path: $PATH_ENV"
